logging:
  level:
    com.example.demo: DEBUG

server:
  port: 8180
  servlet:
    context-path: /api/server

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/iotserver
    username: app
    password: app
    driver-class-name: org.postgresql.Driver
    dbcp2:
      test-while-idle: true
      validation-query: SELECT 1
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true